### ISSUE TITLE
Inconsistent File Path Separator Display in Drivechain Launcher on Windows 10

### ISSUE THREAD

**Issue by seriouscatsoserious** [LayerTwo-Labs/drivechain_launcher#22]
### Description
The Drivechain Launcher on Windows 10 is displaying file paths with forward slashes (`/`) instead of the expected backward slashes (`\`) for Windows file systems. This inconsistency might lead to confusion or issues when users copy and paste these paths in environments that expect the typical Windows path format.

#### Environment
- **OS:** Windows 10
- **Launcher Version:** 1.2.0
- **Component:** File path display

#### Steps to Reproduce
1. Open the Drivechain Launcher.
2. Navigate to the 'Settings' to view the 'Application Data Directory' and 'Drivechain Data Directory' paths.
3. Observe the format of the file paths displayed.
4. Go to the 'BitAssets Info' section and observe the file paths displayed there.

#### Expected Behavior
File paths should display with backward slashes (`\`) as is standard on Windows.

#### Actual Behavior
File paths are displayed with forward slashes (`/`).

#### Screenshots
![1](https://github.com/LayerTwo-Labs/drivechain_launcher/assets/121734574/d9e5d0a6-eddc-411d-88e7-35064471d2d2)
![2](https://github.com/LayerTwo-Labs/drivechain_launcher/assets/121734574/4d8c125c-37fb-4ec7-b4a5-1ce141784bb4)

#### Additional Context
While this has not yet led to any operational issues, it is a deviation from standard Windows path conventions and may cause problems when paths are used in Windows Explorer or command-line interfaces.

**Comment by 8bitprodigy** [comment]
On it.

**Comment by 8bitprodigy** [comment]
Got it. Pushed. Gonna merge.
