### ISSUE TITLE
Ensure that "reset everything" deletes [.drivechain_launcher] file, especially chain_providers.cfg

### ISSUE THREAD

**Issue by psztorc** [LayerTwo-Labs/drivechain_launcher#30]

**Comment by 8bitprodigy** [comment]
Testing, it seems to delete everything after the second click, though the `.drivechain_launcher_sidechains` directory still remains.

**Comment by seriouscatsoserious** [comment]
Need more separation of concerns with these files and where they live. See #21 for example.
