### ISSUE TITLE
Escaping the settings page can be a little confusing

### ISSUE THREAD

**Issue by CryptAxe** [LayerTwo-Labs/drivechain_launcher#38]
When using the setting page I was confused how to escape back to the main page. The quotes arrow button seems like it would be a "go-back" button here to me. Maybe we remove the back arrow??

![launcher_settings](https://github.com/LayerTwo-Labs/drivechain_launcher/assets/8107318/504cb6a4-e812-448b-81ca-88f43da3dd83)

**Comment by 8bitprodigy** [comment]
I could add a button in the settings page to hide it that duplicates the function of the settings button.
