### ISSUE TITLE
The "Stop" button flashes back to "Run" randomly while mainchain is running

### ISSUE THREAD

**Issue by CryptAxe** [LayerTwo-Labs/drivechain_launcher#40]
The buttons change from "Download" -> "Run" -> "Stop" correctly. However I see the button flash back to saying "Run" for a few milliseconds randomly for mainchain. Does not happen all the time

I will try to capture a recording of this and update.

**Comment by seriouscatsoserious** [comment]
Had this happen briefly but it was only the run button, and on Windows 10.

**Comment by seriouscatsoserious** [comment]
After spending time in the Launcher I'd say this is probably due to the way the state of the buttons is tracked.

in chain_state.gd 

`func _on_get_block_height_request_completed(_result, response_code, _headers, body):
	var res = get_result(response_code, body)
	if res.has("result"):
		var new_height = int(res.result) if typeof(res.result) == TYPE_STRING else res.result
		if height != new_height:
			height = new_height
			Appstate.chain_states_changed.emit()
		if not state == c_state.RUNNING:
			state = c_state.RUNNING
			Appstate.chain_states_changed.emit()
	else:
		if not state == c_state.WAITING:
			state = c_state.WAITING
			Appstate.chain_states_changed.emit()

			
	await get_tree().create_timer(1).timeout 
	request_block_height()`
	
	not sure how best to approach this but I know that's why it is happening.

**Comment by seriouscatsoserious** [comment]
Suggested soluton is to change what is a request that happens every second to an asynchronous request that doesn't change the button state until after the response is received and processed
